name: FatJar bauen

on:
  push:
    branches: [ "master" ]

jobs:
  job-fatjar:
    runs-on: ubuntu-latest
    steps:
    - name: Git-Repo auschecken
      uses: actions/checkout@v4
    - name: JDK einrichten
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven
    - name: Permissions von Maven-Wrapper fixen
      run: chmod u+x mvnw
    - name: FatJar-Datei mit Maven bauen
      run: ./mvnw --batch-mode clean test

